spring.application.name=springboot1er
server.port=9090
game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3
game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

spring.datasource.url=jdbc:postgresql://localhost:5432/squaregames
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
